statisticsapi:
  replicaCount: 1
  image:
    repository: balese/statistics-api
    pullPolicy: Always
    digest: "56a47c162feed0f9857072d3d8409dcd7769303a4ddfa3b21e1f8ed916173572"
  secret:
    name: lbsite-tst-db
  service:
    type: NodePort
    port: 8082
    targetPort: 8082
    nodePort: 30082
  env:
    DEVICE_REGISTRATION_URL: http://lbsite-tst-deviceregapi:8081
    SPRING_DATASOURCE_URL: jdbc:postgresql://lbsite-tst-postgresql:5432/lbsite
deviceregapi:
  replicaCount: 1
  image:
    repository: balese/device-registration-api
    pullPolicy: Always
    digest: "4eb8ff81f2d8b1f15edd5b0bec521778cff51f75bac773253d94cc572442c624"
  secret:
    name: lbsite-tst-db
  service:
    port: 8081
    targetPort: 8081
  env:
    SPRING_DATASOURCE_URL: jdbc:postgresql://lbsite-tst-postgresql:5432/lbsite
