apiVersion: v2
name: lbsite
version: 0.1.2
description: Umbrella chart for lbsite applications
appVersion: "0.1.2"
dependencies:
  - name: deviceregapi
    version: 1.0.0
    repository: "file://charts/deviceregapi"
  - name: statisticsapi
    version: 1.0.0
    repository: "file://charts/statisticsapi"
  - name: smartapi
    version: 1.0.0
    repository: "file://charts/smartapi"
