# values-tst.yaml for lbsite umbrella chart (TST environment)

# Docker pull secret for private images
imagePullSecrets:
  - name: regcred

# Device Registration API
deviceregapi:
  replicaCount: 1
  image:
    repository: balese/deviceregapi
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Statistics API
statisticsapi:
  replicaCount: 1
  image:
    repository: balese/statistics-api
    tag: latest@sha256:09265b2aac11e3c122d9f7cf5a5acdb6ca604f9449594adba7dad7291bc509b4
    pullPolicy: Always
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Smart API
smartapi:
  replicaCount: 1
  image:
    repository: balese/smartapi
    tag: latest@sha256:c10b9ae8d69fdca5e53af2675c01177e89377105ab0599c55db4a251d2947dff
    pullPolicy: Always
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
