deviceregapi:
  replicaCount: 1
  image:
    repository: efintechb/deviceregapi
    tag: "latest"

statisticsapi:
  replicaCount: 1
  image:
    repository: efintechb/statisticsapi
    tag: "latest"

smartapi:
  replicaCount: 1
  image:
    repository: efintechb/smartapi
    tag: "latest"
