deviceregapi:
  replicaCount: 1
  image:
    repository: efintechb/deviceregapi
    tag: "1.0.0"

statisticsapi:
  replicaCount: 1
  image:
    repository: efintechb/statisticsapi
    tag: "1.0.0"

smartapi:
  replicaCount: 1
  image:
    repository: efintechb/smartapi
    tag: "1.0.0"
