# values-tst.yaml for lbsite umbrella chart (TST environment)

# Docker pull secret for private images
imagePullSecrets:
  - name: regcred

# Device Registration API
deviceregapi:
  replicaCount: 1
  image:
    repository: balese/deviceregapi
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Statistics API
statisticsapi:
  replicaCount: 1
  image:
    repository: balese/statisticsapi
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Smart API
smartapi:
  replicaCount: 1
  image:
    repository: balese/smartapi
    tag: latest@sha256:3492cfe02ad7744a34023411c291109b83d87c9f5f2261f5412d09ce50a3e93d
    pullPolicy: Always
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
