# values-tst.yaml for lbsite umbrella chart (TST environment)

# Docker pull secret for private images
imagePullSecrets:
  - name: regcred

# Device Registration API
deviceregapi:
  replicaCount: 1
  image:
    repository: balese/device-registration-api
    tag: latest@sha256:eb06786e98b675d5649f80a53334cc0b66281e44777e1c2b7a5aa3e2b70dd355
    pullPolicy: Always
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Statistics API
statisticsapi:
  replicaCount: 1
  image:
    repository: balese/statistics-api
    tag: latest@sha256:a1ed179c0e2b591bfa77dda4d7b0848dab4aba5b11f43cb619fa4e0682943e55
    pullPolicy: Always
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Smart API
smartapi:
  replicaCount: 1
  image:
    repository: balese/smartapi
    tag: latest@sha256:9cb559d6560d2fc3c55cf08cd38fc05dc0234b84f3b4d050e4a819da745873d5
    pullPolicy: Always
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
